Shop: Fixup regression
The following error was issued while having pokémart items enabled:
   Uncaught TypeError: this.__internal__isPokeMarkUnlocked is not a function

The class is now bound properly